delete_data_task:
  client: Transmission
  host: http://transmission:9091
  username:
  password:
  strategies:
    delete_after_seed:
      categories:
        - /downloads/tv
        - /downloads/video
      remove: seeding_time > 3600
    delete_when_stopped:
      categories:
        - /downloads/tv
        - /downloads/video
      status:
        - Stopped
        - Downloading
      remove: last_activity > 3600
  delete_data: true