my_task:
  client: Transmission
  host: http://192.168.0.60:9091
  username:
  password:
  strategies:
    delete_after_seed:
      categories:
        - /downloads/tv
        - /downloads/video
      remove: seeding_time > 300
    delete_when_stopped:
      categories:
        - /downloads/tv
        - /downloads/video
      status:
        - Stopped
      remove: last_activity > 300
  delete_data: true