my_task:
  client: Transmission
  host: http://192.168.0.60:9091
  username:
  password:
  strategies:
    my_strategy:
      categories:
        - /downloads/tv
        - /downloads/video
      status:
        - Stopped
      remove: seeding_time > 300
  delete_data: true